site_name: EnderChest Documentation
repo_url: https://github.com/OpenBagTwo/EnderChest
repo_name: EnderChest
docs_dir: docs
theme:
  name: material
nav:
  - Home: index.md
  - About: about.md
  - API: reference/
markdown_extensions:
  - pymdownx.superfences
  - codehilite
plugins:
  - search
  - mike
  - gen-files:
      scripts:
      - docs/gen_apidocs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
#      handlers:
#        python:
#          docstring_style: numpy
      watch:
        - enderchest
