site_name: EnderChest Documentation
repo_url: https://github.com/OpenBagTwo/EnderChest
repo_name: EnderChest
site_author: Gili "OpenBagTwo" Barlev
docs_dir: docs
edit_uri: ''
theme:
  name: material
  favicon: img/favicon.png
  logo: img/enderchest.png
  features:
  - content.code.copy
nav:
- Home: index.md
- About: about.md
- Installation Instructions: installation.md
- Quick-Start Guide: usage.md
- Best Practices: suggestions.md
- Contribution Guide: contrib.md
- Full CLI Documentation: cli.md
- Python API Docs: reference/
plugins:
- search
- autorefs
- mike
- gen-files:
    scripts:
    - docs/gen_clidocs.py
    - docs/gen_apidocs.py
- section-index
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          enable_inventory: true
watch:
- enderchest
extra:
  version:
    provider: mike
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- admonition
- pymdownx.details
- sane_lists
