# Checks performed on all pull requests, to any branch. Thus, required for protected branches,
# but enables a workflow for CI validation against non-protected branches as well.

name: Python application

on:
  pull_request

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Rsync
      uses: GuillaumeFalourd/setup-rsync@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mypy black isort flake8 pytest-cov
    - name: Autolint as needed
      run: |
        isort . --profile="black"
        black .
        # if nothing has changed, this won't do anything
        git add .
        git commit -m "Emptying the lint trap"
    - name: Run code quality checks
      run: |
        mypy .
        flake8 .
    - name: Run unit tests
      run: |
        pytest -vv --cov=enderchest
