# Checks performed on all pull requests, to any branch. Thus, required for protected branches,
# but enables a workflow for CI validation against non-protected branches as well.

name: PR checker

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install .[test] pre-commit
        pre-commit install
    - name: Run code quality checks
      run: |
        pre-commit run --all
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
    - name: Install Rsync
      if: matrix.os == 'macos-latest'
      run: brew install rsync
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Run unit tests
      run: |
        pytest -vv --doctest-modules --cov=enderchest --ignore-glob="docs/**" --log-level=DEBUG
