# Checks performed on all pull requests, to any branch. Thus, required for protected branches,
# but enables a workflow for CI validation against non-protected branches as well.

name: PR checker

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install . pre-commit
        pre-commit install
    - name: Run code quality checks
      run: |
        pre-commit run --all
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
    - name: Setup Rsync
      uses: GuillaumeFalourd/setup-rsync@v1.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Run unit tests
      run: |
        pytest -vv --doctest-modules --cov=enderchest --ignore-glob="docs/**"
    - name: configure git
      if: ${{ (matrix.os == 'ubuntu-latest') }} && ${{ (matrix.py == '3.11') }}
      run: |
        git config --global user.name docs-golem
        git config --global user.email losthemobvote@openbagtwo.net
    - name: Create coverage badge
      if: ${{ (matrix.os == 'ubuntu-latest') }} && ${{ (matrix.py == '3.11') }}
      uses: tj-actions/coverage-badge-py@v2
    - name: Verify Changed files
      if: ${{ (matrix.os == 'ubuntu-latest') }} && ${{ (matrix.py == '3.11') }}
      uses: tj-actions/verify-changed-files@v14
      id: verify-changed-files
      with:
        files: coverage.svg
    - name: Commit files
      if: ${{ (matrix.os == 'ubuntu-latest') }} && ${{ (matrix.py == '3.11') }} && ${{ (steps.verify-changed-files.outputs.files_changed == 'true') }}
      run: |
        git add coverage.svg
        git commit -m "Update coverage badge"
    - name: Push changes
      if: ${{ (matrix.os == 'ubuntu-latest') }} && ${{ (matrix.py == '3.11') }} && ${{ (steps.verify-changed-files.outputs.files_changed == 'true') }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.github_token }}
        branch: ${{ github.ref }}
