# Checks performed on all pull requests, to any branch. Thus, required for protected branches,
# but enables a workflow for CI validation against non-protected branches as well.

name: PR checker

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mypy black isort flake8 pytest-cov
    - name: Run code quality checks
      run: |
        isort . --profile="black"
        black .
        flake8 .
    - name: Type check with mypy
      run: |
        mypy .
  test:
    runs-on: [ubuntu-latest, windows-latest]  # TODO: bring back macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Rsync
      uses: GuillaumeFalourd/setup-rsync@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mypy black isort flake8 pytest-cov
    - name: Run unit tests
      run: |
        pytest -vv --cov=enderchest
      
